name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature-*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Vérifier la structure du projet
        run: ls -la

      - name: Exécuter un test basique
        run: echo "✅ Le pipeline fonctionne correctement !"
